import type { CreativePromptBundle } from "@/types/creative";
import { BRAND_CONFIG } from "@/config/brand";

export function bundleToText(bundle: CreativePromptBundle): string {
  const lines: string[] = [];

  lines.push(`# ${bundle.title}`);
  lines.push(`> Generated by ${BRAND_CONFIG.name} Creative Studio — ${bundle.generatedAt}`);
  lines.push(`> Medium: ${bundle.medium} | Style: ${bundle.style} | Platform: ${bundle.platform}`);
  lines.push(`> Quality Score: ${bundle.qualityScore}/10`);
  lines.push(`> Active Agents: ${bundle.activeAgents.join(", ")}\n`);

  lines.push(`---\n## Text Prompt\n`);
  lines.push(bundle.textPrompt);
  lines.push(``);

  lines.push(`---\n## Negative Prompt\n`);
  lines.push(bundle.negativePrompt);
  lines.push(``);

  lines.push(`---\n## JSON Prompt (Structured)\n`);
  lines.push("```json");
  lines.push(JSON.stringify(bundle.jsonPrompt, null, 2));
  lines.push("```\n");

  lines.push(`---\n## Platform Notes (${bundle.platform})\n`);
  lines.push(bundle.platformNotes);
  lines.push(``);

  return lines.join("\n");
}

function triggerDownload(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadCreativeMarkdown(bundle: CreativePromptBundle) {
  const md = bundleToText(bundle);
  const safeName = bundle.title.replace(/[^a-zA-Z0-9-_ ]/g, "").replace(/\s+/g, "-").toLowerCase();
  triggerDownload(md, `${safeName}-creative-prompt.md`, "text/markdown");
}

export function downloadCreativeJSON(bundle: CreativePromptBundle) {
  const json = JSON.stringify(bundle, null, 2);
  const safeName = bundle.title.replace(/[^a-zA-Z0-9-_ ]/g, "").replace(/\s+/g, "-").toLowerCase();
  triggerDownload(json, `${safeName}-creative-prompt.json`, "application/json");
}

export function downloadTextPromptOnly(bundle: CreativePromptBundle) {
  const safeName = bundle.title.replace(/[^a-zA-Z0-9-_ ]/g, "").replace(/\s+/g, "-").toLowerCase();
  triggerDownload(bundle.textPrompt, `${safeName}-text-prompt.txt`, "text/plain");
}
