import type { FinalBundle } from "@/types";

export function bundleToMarkdown(bundle: FinalBundle): string {
  const lines: string[] = [];
  const { prd, architecture, testPlan, critique } = bundle.sections;

  lines.push(`# ${bundle.title}`);
  lines.push(`> Generated by Artifexa Product Studio — ${bundle.generatedAt}`);
  lines.push(`> Quality Score: ${bundle.qualityScore}/10\n`);
  lines.push(`## Executive Summary\n${bundle.executiveSummary}\n`);

  // PRD Section
  lines.push(`---\n## Product Requirements Document\n`);
  lines.push(`### Objective\n${prd.prd.objective}\n`);
  lines.push(`### Features\n`);
  lines.push(`| # | Feature | Priority | Phase |`);
  lines.push(`|---|---------|----------|-------|`);
  prd.prd.features.forEach((f, i) => {
    lines.push(`| ${i + 1} | **${f.name}** — ${f.description} | ${f.priority} | ${f.phase} |`);
  });
  lines.push(``);
  lines.push(`### Phases\n`);
  prd.prd.phases.forEach((p) => {
    lines.push(`#### Phase ${p.phase}: ${p.name} (${p.estimatedDuration})`);
    p.deliverables.forEach((d) => lines.push(`- ${d}`));
    lines.push(``);
  });
  lines.push(`### User Journeys\n`);
  prd.userJourneys.forEach((j) => {
    lines.push(`**${j.persona}** — ${j.scenario} ${j.happyPath ? "(Happy Path)" : "(Edge Case)"}`);
    j.steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    lines.push(``);
  });
  lines.push(`### Edge Cases\n`);
  prd.edgeCases.forEach((e) => lines.push(`- ${e}`));
  lines.push(``);

  // Architecture Section
  lines.push(`---\n## Technical Architecture\n`);
  lines.push(`### Tech Stack\n`);
  lines.push(`- **Frontend**: ${architecture.techStack.frontend.join(", ")}`);
  lines.push(`- **Backend**: ${architecture.techStack.backend.join(", ")}`);
  lines.push(`- **Database**: ${architecture.techStack.database.join(", ")}`);
  lines.push(`- **Infrastructure**: ${architecture.techStack.infrastructure.join(", ")}`);
  lines.push(`- **Reasoning**: ${architecture.techStack.reasoning}\n`);
  lines.push(`### High-Level Design\n${architecture.hld.overview}\n`);
  lines.push(`#### Components\n`);
  architecture.hld.components.forEach((c) => {
    lines.push(`- **${c.name}**: ${c.responsibility} (communicates with: ${c.communicatesWith.join(", ")})`);
  });
  lines.push(`\n#### Data Flow\n${architecture.hld.dataFlowDescription}\n`);
  lines.push(`### Low-Level Design\n`);
  lines.push(`#### API Endpoints\n`);
  lines.push(`| Method | Path | Description |`);
  lines.push(`|--------|------|-------------|`);
  architecture.lld.apiEndpoints.forEach((e) => {
    lines.push(`| ${e.method} | \`${e.path}\` | ${e.description} |`);
  });
  lines.push(``);
  lines.push(`#### Database Schema\n`);
  architecture.lld.dbSchema.forEach((t) => {
    lines.push(`**${t.table}**`);
    lines.push(`| Column | Type | Constraints |`);
    lines.push(`|--------|------|-------------|`);
    t.columns.forEach((c) => {
      lines.push(`| ${c.name} | ${c.type} | ${c.constraints || "-"} |`);
    });
    if (t.relationships?.length) {
      lines.push(`Relationships: ${t.relationships.join(", ")}`);
    }
    lines.push(``);
  });
  if (architecture.scalabilityNotes?.length) {
    lines.push(`### Scalability Notes\n`);
    architecture.scalabilityNotes.forEach((n) => lines.push(`- ${n}`));
    lines.push(``);
  }

  // QA Section
  lines.push(`---\n## Test Plan\n`);
  lines.push(`### Strategy\n${testPlan.testStrategy}\n`);
  lines.push(`### Test Cases\n`);
  lines.push(`| ID | Scenario | Priority | Type |`);
  lines.push(`|----|----------|----------|------|`);
  testPlan.testCases.forEach((tc) => {
    lines.push(`| ${tc.id} | ${tc.scenario} | ${tc.priority} | ${tc.type} |`);
  });
  lines.push(``);
  testPlan.testCases.forEach((tc) => {
    lines.push(`#### ${tc.id}: ${tc.scenario}`);
    tc.steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    lines.push(`**Expected**: ${tc.expectedResult}\n`);
  });

  // Critique Section
  lines.push(`---\n## Quality Review\n`);
  lines.push(`**Score**: ${critique.score}/10\n`);
  lines.push(`${critique.summary}\n`);
  if (critique.issues.length > 0) {
    lines.push(`### Issues Found\n`);
    critique.issues.forEach((issue) => {
      lines.push(`- **[${issue.severity.toUpperCase()}] ${issue.area}**: ${issue.description}`);
      lines.push(`  - Suggestion: ${issue.suggestion}`);
    });
  }

  return lines.join("\n");
}

export function triggerDownload(content: string, fileName: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadMarkdown(bundle: FinalBundle) {
  const md = bundleToMarkdown(bundle);
  const safeName = bundle.title.replace(/[^a-zA-Z0-9-_ ]/g, "").replace(/\s+/g, "-").toLowerCase();
  triggerDownload(md, `${safeName}-product-studio.md`, "text/markdown");
}

export function downloadJSON(bundle: FinalBundle) {
  const json = JSON.stringify(bundle, null, 2);
  const safeName = bundle.title.replace(/[^a-zA-Z0-9-_ ]/g, "").replace(/\s+/g, "-").toLowerCase();
  triggerDownload(json, `${safeName}-product-studio.json`, "application/json");
}
